## Python for Data Science and Machine Learning Bootcamp:By Jose Portilla

### This is 25 hour long course by udemy : Date registered for the course April 26, 2020

## This vourse will include the following topics:

### NumPy,SciPy,Pandas,Seaborn,Scikit-Learn,MatplotLib,plotly,PySpark and much more....

In [7]:
#How do you get the Docstring and method list pop-ups in Jupyter Notebook?
# For example, given: my_list = [1,2,3] you could then run that cell to define my_list as a variable,
# afterwards you could just type: my_list. (notice the dot) and then press Tab to see the list of methods.
# For the doctrings of functions, use Shift+Tab with your cursor right after the function.


In [15]:
num =12
name='Bishnu'
print(f"my number is: {num} and my name is: {name}")

my number is: 12 and my name is: Bishnu


In [18]:
nest =[1,2,3,[4,5,['target']]]
print(nest[3])

[4, 5, ['target']]


In [19]:
nest =[1,2,3,[4,5,['target']]]
print(nest[3][2])

['target']


In [24]:
nest =[1,2,3,[4,5,['target']]]
print(nest[3][2][0])

target


In [20]:
ls1 = [2,3,4,5]
ls1[0]="hw"
print(ls1)

['hw', 3, 4, 5]


## Dictionaries

In [28]:
d = {'key1':'item1','key2':'item2'}
print(d)
print(d['key1'])

{'key1': 'item1', 'key2': 'item2'}
item1


In [32]:

tu = (0,2,4,6,9)
print(tu)
print(tu[3])
tu[0] = 'hello'  #tuple can not be changed that is tuple  is immutable
print(tu)


(0, 2, 4, 6, 9)
6


TypeError: 'tuple' object does not support item assignment

## set

In [33]:
se = {1,2,3,4,56,1,2,3,4,5,6,1,2,3,45}#unique
print(se)

{1, 2, 3, 4, 5, 6, 45, 56}


In [34]:
print(1>2)

False


In [35]:
print(1<2)

True


In [37]:
for i in range(1,12,3):
    print('yup!')

yup!
yup!
yup!
yup!


In [38]:
seq = [1,2,3,4,5]
for i in seq:
    print(i+i)

2
4
6
8
10


## List comprehension

In [41]:
ls = [2,4,6,8]
out_put = []
for i in ls:
    out_put.append(i**2)
print(out_put)

[4, 16, 36, 64]


## Lets use the list comprehension method

In [42]:
out_put1 = [i**2 for i in ls]
print(out_put1)

[4, 16, 36, 64]


In [48]:
tweet ='Go Sports!#Sports'  # meaning separate by #
tweet.split('#')


['Go Sports!', 'Sports']

In [49]:
d.keys()

dict_keys(['key1', 'key2'])

In [50]:
d.items()

dict_items([('key1', 'item1'), ('key2', 'item2')])

## Up to here is the basic python crash course

## From here is the data science course

# 1. NumPy 

1.numpy is a linear aljebra library for python. The reason it  is
important for the data science with python is that almost all of the libraries in the pdata ecosystem rely on numpy as one of their main building block.  

2. NumPy is also incredibly fast as it has bindings to C libraries

Highly recommend to install the python using the anaconda distribution to make sure all underlying 
dependencies such as linear aljebra libraries all sync up with the use of the  conda install

if you have anaconda install, install numpy by going to your terminal or command prompt 
and typing
         "conda install numpy"  
      if you do not have anaconda distribution you can simply do the following
    "pip install numpy"

NumPy arrary essentially come in two flavours; 

vectors are strictly  1-d arrays and matrices are 2-d but matrix may have only one row or one column

# How to Creste NumPy Arrays?

NumPy arrays comes in to two flavors 1-d vectors and 2-d matrices

matrix could have only one row or only one column

lets create one dimensional array form a python object lets say from a list

In [52]:
my_list = [1,2,3,4,5]
print(my_list)  #Here my_list is a python object

[1, 2, 3, 4, 5]


In [53]:
import numpy as np
np.array(my_list)

array([1, 2, 3, 4, 5])

we  can store the array in a variable

In [54]:
arr = np.array(my_list)
print(arr) #will give a one dimensional array

[1 2 3 4 5]


## Two dimenaional array

have to start with a list of the following form 

In [57]:
my_mats= [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mats)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

lets assign in a variable 

In [58]:
arr2 = np.array(my_mats)
print(arr2) # will give the two dimensional array
# two big bracket at the opening or two big bracket at the end means 2 d array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## generation method is faster and coool  method to generate the arrays

In [ ]:
#np.arange(0,10)# to see the details about the arange().Put cursor inside the () and press shoift + tab button
# it has a atart argement and that of the stop argument
# np.arange(0,10) means will go  0 to 9 the stop argument is not included
# can add another argument the spet argument as well that gives the steps

In [63]:
ar = np.arange(0,10)# will print from 0 to 9
ar2 = np.arange(0,100,10)# will print at the interval of 10
print(ar)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]


In [64]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## how to generate an array of zeroes?

In [65]:
np.zeros(5) # I would like to print 5 zeros

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((5,4))# for a two dimensional array provide a tuple
# first number ie 5  represent number of rows and the second number(4) represent the no of  column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## generate the array of ones

for a one dimensional array just one argunment and for the 2 d array 2 argument

In [68]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [71]:
np.ones((2,3)) # two rows and 3 columns in the  form of a tuple

array([[1., 1., 1.],
       [1., 1., 1.]])

## linspace method to generate the array


Signature: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.


In [72]:
np.linspace(0,5,10)# means between 0 and 5 ..... 10 evenly spaced numbers over the interval 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [74]:
np.linspace(0,50,20) # note this is the one dimendionsl srrsy

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

## how to create the identity matrix using the numpy

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.




In [75]:
np.eye(4) # 2nd order matrix, no of rows  = no of columns
# Note the identity matrix is always in the square form

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## How to create the random number

np.random.rand()

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.



In [78]:
np.random.rand(5)# 1-d array, uniformaly distributed between 0 and that of  1

array([0.84730439, 0.96683025, 0.61172275, 0.11000687, 0.59606886])

In [79]:
np.random.rand(5,4)# here 5,4 4 are the arguments


array([[0.65117689, 0.4291532 , 0.77452618, 0.892083  ],
       [0.23624208, 0.76884874, 0.32816767, 0.07268737],
       [0.6449514 , 0.62466217, 0.71783077, 0.2715181 ],
       [0.15692685, 0.12277862, 0.73095112, 0.83239509],
       [0.23736444, 0.04498367, 0.56723459, 0.09948877]])

## np.random.randn

it will return the standard normal distribution centered at zero

In [81]:
np.random.randn(2)# from a standard normal distribution

array([-0.05147358,  0.4914085 ])

can have a two dimensional 

In [82]:
np.random.randn(2,3)

array([[ 0.00347583,  0.62801023, -0.9056351 ],
       [-2.79681196, -0.99774637,  2.13723955]])

## final random method of creating array: 

retuns the random integer from a low to high number

Docstring:
randint(low, high=None, size=None, dtype='l')

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

Parameters
----------
low : int
    Lowest (signed) integer to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. All dtypes are determined by their
    name, i.e., 'int64', 'int', etc, so byteorder is not available
    and a specific precision may have different C types depending
    on the platform. The default value is 'np.int'.


In [84]:
np.random.randint(1,100)# will get a random number between 0 & 100

49

In [85]:
np.random.randint(1,100,10)# lower end inclusive, higher end exclusive

array([70, 89, 95,  5, 39, 98,  8, 32, 88, 39])

## some useful attributes and methods of array

In [86]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
randarr=np.random.randint(0,50,10)
randarr

array([13, 14, 34, 26, 17, 33, 21, 25, 15,  3])

## reshape method 

In [89]:
arr.reshape(5,5) # arr is reshaped 
#make sure size of the matrix should be ok for example
# arr has 25 elements and here we did 5X5 also has 25 elements
# That means no of rows * no of columns = total no of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## How to find the max value in the array?

arr.max()

In [91]:
arr.min()

0

To see the index location of the element

In [92]:
arr.argmax()

24

In [96]:
randarr.max()

34

In [97]:
randarr.argmax()

2

In [98]:
randarr.argmin()

9

In [99]:
arr.shape  # that means it iis the one dimensional vector

(25,)

In [100]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
arr.shape # means 2 d now  # make sure no parenthesis

(5, 5)

In [102]:
arr.shape()

TypeError: 'tuple' object is not callable

## How to find the data type in the array

In [103]:
arr.dtype  # it says integer 64 bit


dtype('int64')

## Another nice method to create the random integer

In [104]:
from numpy.random import randint
randint(2,10)

9

In [105]:
from numpy.random import randint
randint(2,10,5)

array([4, 6, 7, 7, 2])

# Secod lecture on NumPy 

## NumPy array indexing and Selection

In [107]:
import numpy as np
arr=np.arange(0,11)
arr # now I ahve 11 elements from 0 to 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

SImplest way to pick out one or more elements of an array looks  like a lot like indexing from python

### It works exactly like a normal python list

In [108]:
arr[8]

8

In [109]:
arr[1:5]

array([1, 2, 3, 4])

In [110]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [111]:
arr[:5]

array([0, 1, 2, 3, 4])

In [112]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
arr[5:]# grab everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

In [116]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

lets reset the array again

In [117]:
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [118]:
slice_arr=arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [120]:
slice_arr[:]=199
slice_arr


array([199, 199, 199, 199, 199, 199])

In [121]:
arr # the original array is changed not only the slice changed

array([199, 199, 199, 199, 199, 199,   6,   7,   8,   9,  10])

In [122]:
arr_copy=arr.copy()
arr_copy

array([199, 199, 199, 199, 199, 199,   6,   7,   8,   9,  10])

In [123]:
arr_copy[0:5]=100
arr_copy

array([100, 100, 100, 100, 100, 199,   6,   7,   8,   9,  10])

In [124]:
arr # the original array is not addected

array([199, 199, 199, 199, 199, 199,   6,   7,   8,   9,  10])

So the conclusion is that if we make a copy of an array and make a slice of the copy and change some elements of that slice,
the original array is not affacted. But if we make a slice of an array and change some elements of that slice that will change 
the orignal array

## Indexing in the 2-d array

In [125]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d # will have a 2d array with 3 rows and that of 3 columns

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

There are two generl formats for grabbing the elements from the 2-d array or fro the matrix 

1. double bracket method ( that is [i][j]  where i = row and [j] = column)

In [126]:
arr_2d[0][0] # the first [0] belong to the row and the second [0] belong to the column 

5

In [127]:
arr_2d[2][1]# like to grab 40

40

2. Single bracket method ( that is [i, j] where i = row and j = column)

In [ ]:
# I would like to grab 40 again by this method

In [129]:
arr_2d[2,1] #Note: the one set of  bracket is replaced by a comma


40

## How to extracct the submatrices in setesd of grabing a single element

I would like to grab the top right corner of the matrix that is like to grab the following                                                                                     10  15                                                                    
25  30
                            

In [131]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
# lets grab 20. 25, 20 
# and       35,40, 45

In [132]:
arr_2d[1:]



array([[20, 25, 30],
       [35, 40, 45]])

array([[25, 30],
       [40, 45]])

# Conditional selection

In [135]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
bool_arr = arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [141]:
arr[bool_arr] # will get the result only when the boolean array is true

array([ 6,  7,  8,  9, 10])

The same thing can be done in the one line

In [142]:
arr[arr>5] # very important

array([ 6,  7,  8,  9, 10])

 Now I am going to select only those  element of the array which are less than 6

In [143]:
arr[arr<6] # will return all true 

array([1, 2, 3, 4, 5])

# Practice example

In [145]:
arr_2d1 = np.arange(50).reshape(5,10)
arr_2d1


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#lets grab some sub matrices
                27   28
                37   38
       

In [146]:
arr_2d1[2:4]  # may be this is the first part to understand the process

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [147]:
arr_2d1[2:4,7:9] 

array([[27, 28],
       [37, 38]])

## NumPy Operations

basic operations with the numpy arrays

Array with array.                                                                                           
Array with scalars.
                                                                                     
                                                                                     
Universal Array functions

In [149]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

How to add two array together on element by element basis

In [150]:
arr + arr # will add the two array  together

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

can do the subtraction and also the multilication

In [151]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [152]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

can perform array with the scalar operation

the operations occurs the element by element method

In [154]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
arr+ 100 # every element will be the element + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [155]:
arr*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

## Note: can do the subtraction and the division as well

some time python gives some warning messages

In [157]:
1/0 # The following error is ok as a umber is not divisible by 0

ZeroDivisionError: division by zero

In [160]:
arr/arr # This is the warning message . The first element in the array was 0 . So it is like 0/0. and it 
# outputs "nan" in stead of the ZeroDivisionError  

/home/bishnu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### What if the number is divided by 0?

it will display infinity

In [161]:
1/arr#element is  the first  infinity which is actually 1/0

/home/bishnu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

## Can do the array eponent that is arr**2

In [162]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Universal array function

How to take the square root of the each element of the array

In [163]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [164]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [165]:
np.max(arr)

10

## Can do the trignometric operations with the array

In [166]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

Also have the logerethmic functions for array

In [168]:
np.log(arr)# since log(0) is the negative infinnity . Therefore it dispalys the warning messages

/home/bishnu/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# NumPy Exercises

In [169]:
import numpy as np

Create an array of 10 zeros

In [170]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [173]:
ar0= np.ones(10)
ar0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [175]:
ar0=ar0*5
ar0

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [214]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

another method

In [215]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [216]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [217]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [182]:
Ae = np.arange(0,9)
Ae

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [186]:
Ae1 = Ae.reshape(3,3) #1st method
Ae1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [184]:
np.arange(0,9).reshape(3,3)#1st method

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix¶

In [187]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1¶

In [192]:
np.random.rand()

0.057153135315082815

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [194]:
np.random.randn(25)

array([-0.02241163, -0.3081925 , -1.51062113, -0.56494173, -2.38690739,
       -1.56284981,  2.4156476 , -0.65296627,  2.55258843, -0.74476988,
        0.7466952 ,  0.3619851 ,  2.33332467,  0.83295878,  1.59331051,
        0.57947053,  1.78445067, -0.80092403,  0.58131304, -0.84116298,
        1.14147482,  0.43503648,  0.57971455, -0.45980263,  2.26469164])

Create the following matrix

First way to do this solution is 

In [227]:
np.arange(1,101).reshape(10,10)/10

array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [223]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of 20 linearly spaced points between 0 and 1:

In [198]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [199]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
 BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
 BE ABLE TO SEE THE OUTPUT ANY MORE

In [200]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [204]:
mat[3][4]

20

In [205]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [206]:
mat[4]

array([21, 22, 23, 24, 25])

In [207]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

Get the sum of all the values in mat

### How to sum the all  of the elements of a matrix?

In [209]:
mat.sum()# gives the sum of the all of the elemensts in the matrix

325

In [228]:
np.sum(mat)

325

### How to get the satndard deviation of a matrix?

In [210]:
mat.std()


7.211102550927978

In [229]:
np.std(mat)

7.211102550927978

## How to get the sum of the columns or rows in a matrix?

Get the sum of all the columns in mat

In [212]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

Get the sum of all the columns in mat

In [213]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])